# Generated by Django 5.1.7 on 2025-04-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('price_year', models.CharField(max_length=50, verbose_name='Annual Price')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('stripe_plan_id', models.CharField(max_length=255, unique=True)),
                ('price_str', models.CharField(blank=True, max_length=30)),
                ('interval', models.CharField(blank=True, choices=[('month', 'Monthly'), ('year', 'Yearly')], max_length=20, null=True)),
                ('price_description', models.CharField(max_length=100, verbose_name='Price Description')),
                ('features', models.JSONField(verbose_name='Features')),
                ('requirements', models.JSONField(verbose_name='Requirements')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
            },
        ),
    ]
