# Generated by Django 5.1.7 on 2025-04-11 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('price_year', models.CharField(max_length=50, verbose_name='Precio Anual')),
                ('year_description', models.CharField(max_length=100, verbose_name='Descripción Anual')),
                ('price', models.CharField(max_length=50, verbose_name='Precio Único')),
                ('price_description', models.CharField(max_length=100, verbose_name='Descripción del Precio Único')),
                ('features', models.JSONField(verbose_name='Características')),
                ('requirements', models.JSONField(verbose_name='Requisitos')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
            },
        ),
        migrations.RemoveField(
            model_name='suscription',
            name='suscription_cost',
        ),
        migrations.RemoveField(
            model_name='suscription',
            name='suscription_plan',
        ),
        migrations.AddField(
            model_name='suscription',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='suscription',
            name='payment_stripe',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='suscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscription',
            name='plan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='membership.membershipplan'),
            preserve_default=False,
        ),
    ]
