# Generated by Django 5.2.5 on 2025-08-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='access_experts_and_mentees',
            field=models.BooleanField(default=False, verbose_name='Access to The Experts & Mentees'),
        ),
        migrations.AddField(
            model_name='plan',
            name='access_to_forums_and_think_tanks',
            field=models.BooleanField(default=False, verbose_name='Access to The Forum & Think Tanks'),
        ),
        migrations.AddField(
            model_name='plan',
            name='access_to_the_community_forum',
            field=models.BooleanField(default=False, verbose_name='Access to The Community Forum'),
        ),
        migrations.AddField(
            model_name='plan',
            name='dedicated_nobilis_contact',
            field=models.BooleanField(default=False, verbose_name='Dedicated Nobilis Contact'),
        ),
        migrations.AddField(
            model_name='plan',
            name='early_access_to_pre_launch_experiences',
            field=models.BooleanField(default=False, verbose_name='Early Access to Pre-Launch Experiences'),
        ),
        migrations.AddField(
            model_name='plan',
            name='introduction_registration',
            field=models.BooleanField(default=False, verbose_name='Introduction Registration'),
        ),
        migrations.AddField(
            model_name='plan',
            name='member_introduction',
            field=models.BooleanField(default=False, verbose_name='Member Introduction'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nobilis_founder_badge',
            field=models.BooleanField(default=False, verbose_name='Nobilis Founder Badge'),
        ),
        migrations.AddField(
            model_name='plan',
            name='platform_access',
            field=models.BooleanField(default=False, verbose_name='Platform Access'),
        ),
        migrations.AddField(
            model_name='plan',
            name='professional_experience_creation',
            field=models.BooleanField(default=False, verbose_name='Professional Experience Creation'),
        ),
        migrations.AddField(
            model_name='plan',
            name='professional_profile_creation',
            field=models.BooleanField(default=False, verbose_name='Professional Profile Creation'),
        ),
        migrations.AddField(
            model_name='plan',
            name='profile_registration',
            field=models.BooleanField(default=False, verbose_name='Profile Registration'),
        ),
    ]
