# Generated by Django 5.2.5 on 2025-08-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_plan_access_experts_and_mentees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='active_participantion_in_nobilis',
            field=models.BooleanField(default=False, verbose_name='Active Participantion in Nobilis (25k Credits)'),
        ),
    ]
