# Generated by Django 5.1.7 on 2025-04-11 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershipplan_remove_suscription_suscription_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='year_description',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='features',
            field=models.JSONField(verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price_description',
            field=models.CharField(max_length=100, verbose_name='Price Description'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price_year',
            field=models.CharField(max_length=50, verbose_name='Annual Price'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='requirements',
            field=models.JSONField(verbose_name='Requirements'),
        ),
    ]
