# Generated by Django 5.2.5 on 2025-08-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_plan_active_participantion_in_nobilis'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='experience_registration',
            field=models.BooleanField(default=False, verbose_name='Experience Registration'),
        ),
    ]
