# Generated by Django 5.2.5 on 2025-08-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_plan_experience_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='active_participantion_in_nobilis',
        ),
    ]
