# Generated by Django 5.2.5 on 2025-08-28 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_remove_plan_active_participantion_in_nobilis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Shipping Address')),
                ('country', models.CharField(blank=True, max_length=80, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='City')),
                ('card_no', models.CharField(blank=True, null=True, verbose_name='Card Number')),
                ('card_type', models.CharField(blank=True, null=True, verbose_name='Card Type')),
                ('card_last_4', models.CharField(blank=True, null=True, verbose_name='Card Last 4')),
                ('same_billing_address', models.BooleanField(default=False, verbose_name='Billing Address is Same as shipping')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Billing Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shippings',
            },
        ),
    ]
