# Generated by Django 5.2.5 on 2025-08-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
    ]
