# Generated by Django 5.2.5 on 2025-08-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping'),
        ),
    ]
