# Generated by Django 5.2.6 on 2025-09-11 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_plan_shipping'),
        ('nsocial', '0014_userprofile_pic_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.plan')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='nsocial.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_subscription_id'], name='membership__stripe__d0a41a_idx'), models.Index(fields=['status'], name='membership__status_1941f4_idx')],
            },
        ),
    ]
