# Generated by Django 5.2.6 on 2025-09-23 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_introductioncatalog_introductionstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberintroduction',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberintroduction',
            name='introduction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.introductioncatalog'),
        ),
        migrations.AlterField(
            model_name='memberintroduction',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='memberintroduction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.introductionstatus'),
        ),
        migrations.AlterField(
            model_name='memberintroduction',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberintroduction',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
