# Generated by Django 5.2.6 on 2025-09-24 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_alter_memberintroduction_from_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteeQualificationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invitee Qualification',
                'verbose_name_plural': 'Invitee Qualifications',
            },
        ),
        migrations.CreateModel(
            name='MemberReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_referrals', to=settings.AUTH_USER_MODEL)),
                ('invitee_qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='membership.inviteequalificationcatalog')),
            ],
            options={
                'verbose_name': 'Member Referral',
                'verbose_name_plural': 'Member Referrals',
                'ordering': ['-created_at'],
            },
        ),
    ]
