# Generated by Django 5.2.6 on 2025-09-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_inviteequalificationcatalog_memberreferral'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionAnnualLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limits', models.IntegerField()),
            ],
        ),
    ]
