# Generated by Django 5.2.6 on 2025-09-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_introductionannuallimits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntroductionAnnualLimits',
        ),
    ]
