# Generated by Django 5.2.6 on 2025-11-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_delete_introductionannuallimits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='card_last_4',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Card Last 4'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='card_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='card_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Card Type'),
        ),
    ]
