# Generated by Django 5.1.7 on 2025-04-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=25000, verbose_name='E-mail')),
                ('occupation', models.CharField(blank=True, max_length=60, null=True, verbose_name='Occupation')),
                ('country', models.CharField(blank=True, max_length=4, null=True, verbose_name='Country')),
                ('referenced', models.CharField(blank=True, max_length=60, null=True, verbose_name='Referenced')),
                ('option0', models.BooleanField(blank=True, default=False, verbose_name='Engage in a trusted, premium ecosysten tailored to meet your needs')),
                ('option1', models.BooleanField(blank=True, default=False, verbose_name='Connect with a prestigious global network of ultra-high archievers, like yourself')),
                ('option2', models.BooleanField(blank=True, default=False, verbose_name='Building meaningful, outcome-driven relationships for personal and professional growth, with transparent motivation and win-win outcomes')),
                ('option3', models.BooleanField(blank=True, default=False, verbose_name='Create and lead exclusive experiences tha showcase your expertise and passions')),
                ('option4', models.BooleanField(blank=True, default=False, verbose_name='Participate in unique, member-led experiences curated for exclusively Nobilis members')),
                ('option5', models.BooleanField(blank=True, default=False, verbose_name='Gain early access to top-tier market insights for expert knowleage in AI, investment, longevity, and more')),
                ('option6', models.BooleanField(blank=True, default=False, verbose_name='Sharing your expertise and values in a confidential and collaborative setting')),
                ('option7', models.BooleanField(blank=True, default=False, verbose_name='Contributing to a lasting legacy with exceptional individual')),
                ('option8', models.BooleanField(blank=True, default=False, verbose_name='Network while enjoying adventures or spending quality time with family')),
                ('option9', models.BooleanField(blank=True, default=False, verbose_name='Ensure lasting meaningful connections')),
                ('other_option', models.TextField(blank=True, null=True, verbose_name='Other (Please specify)')),
                ('wealth_owner', models.BooleanField(blank=True, default=False, verbose_name='Wealth Owner')),
                ('impact_maker', models.BooleanField(blank=True, default=False, verbose_name='Impact Maker')),
                ('executive', models.BooleanField(blank=True, default=False, verbose_name='Executive')),
                ('governor', models.BooleanField(blank=True, default=False, verbose_name='Governor')),
                ('link_verify', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('status_waiting_list', models.IntegerField(default=0, verbose_name='Status Waiting List')),
            ],
            options={
                'verbose_name': 'Waiting List',
                'verbose_name_plural': 'Waiting Lists',
                'ordering': ['-created_at'],
            },
        ),
    ]
