# Generated by Django 5.1.7 on 2025-03-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=25000, verbose_name='E-mail')),
                ('occupation', models.CharField(blank=True, max_length=60, null=True, verbose_name='Occupation')),
                ('city', models.CharField(blank=True, max_length=60, null=True, verbose_name='City')),
                ('referenced', models.CharField(blank=True, max_length=60, null=True, verbose_name='Referenced')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
        ),
    ]
