# Generated by Django 5.2.5 on 2025-08-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='country',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='referenced',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Referenced'),
        ),
    ]
