# Generated by Django 5.1.7 on 2025-03-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='is_active',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='status_waiting_list',
            field=models.IntegerField(default=0, verbose_name='Status Waiting List'),
        ),
    ]
