# Generated by Django 5.2.6 on 2025-10-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0002_remove_waitinglist_country_waitinglist_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
