# Generated by Django 5.1.7 on 2025-04-01 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0002_remove_waitinglist_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wealth_owner', models.BooleanField(blank=True, null=True, verbose_name='Wealth Owner')),
                ('impact_maker', models.BooleanField(blank=True, null=True, verbose_name='Impact Maker')),
                ('executive', models.BooleanField(blank=True, null=True, verbose_name='Executive')),
                ('governor', models.BooleanField(blank=True, null=True, verbose_name='Governor')),
                ('link_verify', models.CharField(max_length=255, verbose_name='Link')),
                ('fk_waitinglist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='waitinglist.waitinglist')),
            ],
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option0', models.BooleanField(blank=True, null=True)),
                ('option1', models.BooleanField(blank=True, null=True)),
                ('option2', models.BooleanField(blank=True, null=True)),
                ('option3', models.BooleanField(blank=True, null=True)),
                ('option4', models.BooleanField(blank=True, null=True)),
                ('option5', models.BooleanField(blank=True, null=True)),
                ('option6', models.BooleanField(blank=True, null=True)),
                ('option7', models.BooleanField(blank=True, null=True)),
                ('option8', models.BooleanField(blank=True, null=True)),
                ('option9', models.BooleanField(blank=True, null=True)),
                ('other_option', models.TextField(blank=True, null=True)),
                ('fk_waitinlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivation', to='waitinglist.waitinglist')),
            ],
        ),
    ]
