# Generated by Django 5.2.6 on 2025-10-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0003_alter_waitinglist_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='income_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Income Range'),
        ),
    ]
