# Generated by Django 5.1.7 on 2025-04-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0003_category_motivation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='fk_waitinglist',
            new_name='waitinglist',
        ),
        migrations.RenameField(
            model_name='motivation',
            old_name='fk_waitinlist',
            new_name='waitinlist',
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option0',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option4',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option5',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option6',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option7',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option8',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option9',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='other_option',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
