# Generated by Django 5.2.6 on 2025-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0004_waitinglist_income_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='status_waiting_list',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
