# Generated by Django 5.1.7 on 2025-04-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0004_rename_fk_waitinglist_category_waitinglist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='executive',
            field=models.BooleanField(blank=True, default=False, verbose_name='Executive'),
        ),
        migrations.AlterField(
            model_name='category',
            name='governor',
            field=models.BooleanField(blank=True, default=False, verbose_name='Governor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='impact_maker',
            field=models.BooleanField(blank=True, default=False, verbose_name='Impact Maker'),
        ),
        migrations.AlterField(
            model_name='category',
            name='wealth_owner',
            field=models.BooleanField(blank=True, default=False, verbose_name='Wealth Owner'),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option0',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option4',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option6',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option7',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option8',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option9',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
    ]
