# Generated by Django 5.1.7 on 2025-04-02 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0005_alter_category_executive_alter_category_governor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='waitinglist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='waitinglist.waitinglist'),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option0',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option1',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option2',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option3',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option4',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option5',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option6',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option7',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='option8',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='waitinlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivation', to='waitinglist.waitinglist'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
