# Generated by Django 5.2.6 on 2025-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0005_remove_waitinglist_status_waiting_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reject Reason'),
        ),
    ]
