# Generated by Django 5.1.7 on 2025-04-02 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0006_alter_category_id_alter_category_waitinglist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivation',
            name='waitinlist',
        ),
        migrations.AddField(
            model_name='motivation',
            name='waitinglist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='motivations', to='waitinglist.waitinglist'),
        ),
        migrations.AlterField(
            model_name='category',
            name='waitinglist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='waitinglist.waitinglist'),
        ),
    ]
