# Generated by Django 5.2.6 on 2025-10-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0006_waitinglist_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150, verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Rejection Reason',
                'verbose_name_plural': 'Rejection Reasons',
            },
        ),
    ]
