# Generated by Django 5.2.6 on 2025-10-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0007_rejectionreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes'),
        ),
    ]
