# Generated by Django 5.1.7 on 2025-04-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0007_remove_motivation_waitinlist_motivation_waitinglist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivation',
            name='waitinglist',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='executive',
            field=models.BooleanField(blank=True, default=False, verbose_name='Executive'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='governor',
            field=models.BooleanField(blank=True, default=False, verbose_name='Governor'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='impact_maker',
            field=models.BooleanField(blank=True, default=False, verbose_name='Impact Maker'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='link_verify',
            field=models.CharField(default='', max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='option0',
            field=models.BooleanField(blank=True, default=False, verbose_name='Engage in a trusted, premium ecosysten tailored to meet your needs'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='option1',
            field=models.BooleanField(blank=True, default=False, verbose_name='Connect with a prestigious global network of ultra-high archievers, like yourself'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='option2',
            field=models.BooleanField(blank=True, default=False, verbose_name='Building meaningful, outcome-driven relationships for personal and professional growth, with transparent motivation and win-win outcomes'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='option3',
            field=models.BooleanField(blank=True, default=False, verbose_name='Create and lead exclusive experiences tha showcase your expertise and passions'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='option4',
            field=models.BooleanField(blank=True, default=False, verbose_name='Participate in unique, member-led experiences curated for exclusively Nobilis members'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='option5',
            field=models.BooleanField(blank=True, default=False, verbose_name='Gain early access to top-tier market insights for expert knowleage in AI, investment, longevity, and more'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='option6',
            field=models.BooleanField(blank=True, default=False, verbose_name='Sharing your expertise and values in a confidential and collaborative setting'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='option7',
            field=models.BooleanField(blank=True, default=False, verbose_name='Contributing to a lasting legacy with exceptional individual'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='option8',
            field=models.BooleanField(blank=True, default=False, verbose_name='Network while enjoying adventures or spending quality time with family'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='option9',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ensure lasting meaningful connections'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='other_option',
            field=models.TextField(blank=True, null=True, verbose_name='Other (Please specify)'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='wealth_owner',
            field=models.BooleanField(blank=True, default=False, verbose_name='Wealth Owner'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Motivation',
        ),
    ]
