# Generated by Django 5.1.7 on 2025-04-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0008_remove_motivation_waitinglist_waitinglist_executive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='city',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='country',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Country'),
        ),
    ]
