# Generated by Django 5.2.6 on 2025-10-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0008_waitinglist_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectionreason',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waitinglist.rejectionreason', verbose_name='Rejection Reason'),
        ),
    ]
