# Generated by Django 5.1.7 on 2025-04-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0009_remove_waitinglist_city_waitinglist_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitinglist',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
