# Generated by Django 5.1.7 on 2025-04-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0010_rename_lastname_waitinglist_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='link_verify',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
    ]
