# Generated by Django 5.1.7 on 2025-04-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0011_alter_waitinglist_link_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitinglist',
            old_name='name',
            new_name='first_name',
        ),
    ]
