# Generated by Django 5.1.7 on 2025-04-08 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0012_rename_name_waitinglist_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Waiting List', 'verbose_name_plural': 'Waiting Lists'},
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
