# Generated by Django 5.1.7 on 2025-04-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteTmpToken',
            fields=[
                ('user_email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('user_token', models.TextField()),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
