# Generated by Django 5.1.7 on 2025-04-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetmptoken',
            name='user_token',
            field=models.TextField(),
        ),
    ]
