# Generated by Django 5.1.7 on 2025-04-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_invitetmptoken_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetmptoken',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
