# Generated by Django 5.2.5 on 2025-08-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='CityCatalog',
        ),
    ]
