# Generated by Django 5.2.6 on 2025-09-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_relative'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='relative',
            name='email',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='relative',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatives', to='api.relationshipcatalog'),
        ),
    ]
