# Generated by Django 5.2.6 on 2025-09-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_relationshipcatalog_remove_relative_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
