# Generated by Django 5.2.6 on 2025-09-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_relative_year_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Support Agent Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Support Agent Email')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Support Agent Phone Number')),
                ('aviable_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Support Agent',
                'verbose_name_plural': 'Support Agents',
            },
        ),
    ]
