# Generated by Django 5.2.6 on 2025-10-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_clubcatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rate Expertise',
                'verbose_name_plural': 'Rate Expertise',
                'ordering': ['name'],
            },
        ),
    ]
