# Generated by Django 5.2.6 on 2025-10-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo de Contacto')),
            ],
            options={
                'verbose_name': 'Correo de Contacto',
                'verbose_name_plural': 'Correos de Contacto',
            },
        ),
    ]
