# Generated by Django 5.2.6 on 2025-10-23 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contactemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipEnquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(max_length=100, verbose_name='Tipo de Partnership')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('company_name', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Envío')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Partnership Enquiry',
                'verbose_name_plural': 'Partnership Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partner Type',
                'verbose_name_plural': 'Partner Types',
                'ordering': ['name'],
            },
        ),
    ]
