# Generated by Django 5.2.6 on 2025-10-25 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_partnershipenquery_partnertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershipenquery',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enqueries', to='api.partnertype'),
        ),
    ]
