# Generated by Django 5.2.6 on 2025-10-15 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Experiencia')),
                ('city', models.CharField(max_length=100, verbose_name='Lugar/Ciudad')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('duration_in_minutes', models.PositiveIntegerField(verbose_name='Duración en Minutos')),
                ('max_guests', models.PositiveIntegerField(verbose_name='Número de Invitados')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('photo', models.ImageField(upload_to='experience_photos/', verbose_name='Foto Ilustrativa')),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Product ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_experiences', to=settings.AUTH_USER_MODEL, verbose_name='Anfitrión')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='experiences.experience')),
            ],
            options={
                'unique_together': {('experience', 'guest')},
            },
        ),
    ]
