# Generated by Django 5.2.6 on 2025-11-06 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Experience Categories',
            },
        ),
        migrations.CreateModel(
            name='ExperienceOptionalEnhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Experience Optional Enhancements',
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='city',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='duration_in_minutes',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='max_guests',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='stripe_product_id',
        ),
        migrations.AddField(
            model_name='experience',
            name='arrival_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de llegada'),
        ),
        migrations.AddField(
            model_name='experience',
            name='beneficiary_for_profit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Beneficiary for Profit'),
        ),
        migrations.AddField(
            model_name='experience',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='experience_photos/', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='experience',
            name='galery_image',
            field=models.ImageField(blank=True, null=True, upload_to='experience_photos/', verbose_name='Galery Image'),
        ),
        migrations.AddField(
            model_name='experience',
            name='guest_capacity_adults',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad de invitados Adultos'),
        ),
        migrations.AddField(
            model_name='experience',
            name='guest_capacity_children',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad de invitados niños'),
        ),
        migrations.AddField(
            model_name='experience',
            name='guest_capacity_infants',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad de invitados infantes'),
        ),
        migrations.AddField(
            model_name='experience',
            name='host_presence',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Host Presence'),
        ),
        migrations.AddField(
            model_name='experience',
            name='ideal_audience',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Ideal audience'),
        ),
        migrations.AddField(
            model_name='experience',
            name='important_information_guest',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Important information for guests'),
        ),
        migrations.AddField(
            model_name='experience',
            name='itinerary',
            field=models.TextField(blank=True, null=True, verbose_name='Itinerario'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location Address'),
        ),
        migrations.AddField(
            model_name='experience',
            name='optional_addicional_team_members',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Addicional Team Members'),
        ),
        migrations.AddField(
            model_name='experience',
            name='optional_video_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Optional Video Link'),
        ),
        migrations.AddField(
            model_name='experience',
            name='price_per_guest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por invitado'),
        ),
        migrations.AddField(
            model_name='experience',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='what_is_included',
            field=models.TextField(blank=True, null=True, verbose_name='Lo que incluye'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_experiences', to=settings.AUTH_USER_MODEL, verbose_name='Anfitrión'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Experiencia'),
        ),
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='experiences.experiencecategory'),
        ),
    ]
