# Generated by Django 5.1.7 on 2025-04-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
