# Generated by Django 5.2.5 on 2025-08-26 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0002_remove_userprofile_bio_userprofile_alias_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
