# Generated by Django 5.2.5 on 2025-08-27 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0003_remove_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('profile_url', models.URLField(max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_profiles', to='nsocial.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'platform_name')},
            },
        ),
    ]
