# Generated by Django 5.2.5 on 2025-08-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0004_socialmediaprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prefered_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefered_phone',
            field=models.BooleanField(default=False),
        ),
    ]
