# Generated by Django 5.2.5 on 2025-08-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0005_userprofile_prefered_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
