# Generated by Django 5.2.6 on 2025-09-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0006_remove_userprofile_languages_userprofile_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rate', models.CharField(max_length=50)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='nsocial.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_detail', to='nsocial.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='nsocial.personaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industries', models.TextField(blank=True, null=True)),
                ('professional_interest', models.TextField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to='nsocial.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NonProfitInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('from_year', models.CharField(max_length=10)),
                ('to_year', models.CharField(max_length=10)),
                ('professional_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_profit_involvement', to='nsocial.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('carreer', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('from_year', models.CharField(max_length=10)),
                ('to_year', models.CharField(max_length=10)),
                ('professional_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='nsocial.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BoardPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('from_year', models.CharField(max_length=10)),
                ('to_year', models.CharField(max_length=10)),
                ('professional_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_board', to='nsocial.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_accomplishments', models.JSONField(default=list)),
                ('additional_links', models.JSONField(default=list)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recognition', to='nsocial.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('from_year', models.CharField(max_length=10)),
                ('to_year', models.CharField(max_length=10)),
                ('professional_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_positions', to='nsocial.professionalprofile')),
            ],
        ),
    ]
