# Generated by Django 5.2.6 on 2025-09-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0008_uservideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Experiencia')),
                ('photograph', models.ImageField(upload_to='experiences/', verbose_name='Fotografía')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
