# Generated by Django 5.2.6 on 2025-09-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0009_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio_presentation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
