# Generated by Django 5.2.6 on 2025-09-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0010_userprofile_bio_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='photograph',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='street',
        ),
        migrations.AddField(
            model_name='experience',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='experience',
            name='author_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_photograph',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
