# Generated by Django 5.2.6 on 2025-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0011_remove_experience_photograph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
