# Generated by Django 5.2.6 on 2025-09-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0012_experience_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Autor')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='Foto del Autor')),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='author',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='author_pic',
        ),
        migrations.AddField(
            model_name='experience',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='nsocial.author'),
        ),
    ]
