# Generated by Django 5.2.6 on 2025-09-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0013_author_remove_experience_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pic_footer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
