# Generated by Django 5.2.6 on 2025-09-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0017_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='often_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
