# Generated by Django 5.2.6 on 2025-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0018_userprofile_often_in_userprofile_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guiding_principle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
