# Generated by Django 5.2.6 on 2025-09-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0019_userprofile_guiding_principle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='annual_limits_introduction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='life_partner_lastname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='life_partner_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_reports',
            field=models.BooleanField(default=False),
        ),
    ]
