# Generated by Django 5.2.6 on 2025-10-08 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_delete_introductionannuallimits'),
        ('nsocial', '0020_userprofile_annual_limits_introduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntroductionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_introduction_preferences', to='membership.introductioncatalog')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='introduction_preference', to='nsocial.userprofile')),
            ],
            options={
                'verbose_name': 'User Introduction Preference',
                'verbose_name_plural': 'User Introduction Preferences',
            },
        ),
    ]
