# Generated by Django 5.2.6 on 2025-10-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0021_userintroductionpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
