# Generated by Django 5.2.6 on 2025-10-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0022_expertise_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
