# Generated by Django 5.2.6 on 2025-10-25 19:22

import nsocial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsocial', '0023_alter_expertise_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics', validators=[nsocial.models.validate_image_size]),
        ),
    ]
